/**
 * The reading material.
 *
 * Written under three rules, all of them reactions to why guitar theory books
 * do not stick:
 *
 * 1. Every figure is GENERATED by the engine, not drawn by hand. The diagrams
 *    in here cannot drift away from what the tools say, because they come from
 *    the same functions the tools call.
 *
 * 2. It starts from the guitar and from what your hands already do. Not "here
 *    is a minor third, now go find one" but "you already play this shape, and
 *    here is what the parts of it are called".
 *
 * 3. The factual claims are checked. tests/lessons.test.ts asserts that the
 *    numbers written in the prose match the engine - if a chord formula here
 *    says R 3 5 7, a test confirms the registry agrees.
 *
 * Lessons are data rather than markup so all three of those stay possible.
 */

export type ScreenId = 'decoder' | 'dictionary' | 'improv' | 'calibration'

export interface LessonDot {
  string: 1 | 2 | 3 | 4 | 5 | 6
  fret: number
  label?: string
  /** Drawn hollow - a note being pointed at rather than one you hold. */
  ghost?: boolean
}

export type Block =
  /** Prose. Supports **bold** and `code`. */
  | { kind: 'text'; body: string }
  /** A short aside worth setting apart. */
  | { kind: 'note'; body: string }
  /** A fretboard with dots placed by hand. */
  | { kind: 'fretboard'; caption?: string; fretRange: [number, number]; dots: LessonDot[] }
  /** Every tone of a chord across a fret window, labelled in degrees. */
  | { kind: 'chordmap'; caption?: string; chord: string; fretRange: [number, number] }
  /**
   * A row of chord boxes, generated for the standard hand.
   *
   * `stringSet` and `fretRange` pin the shapes down. Without them the generator
   * picks whatever is cheapest for each chord independently, which gives four
   * unrelated grips at four positions - useless for a figure whose whole point
   * is that only one or two dots move.
   */
  | {
      kind: 'chords'
      caption?: string
      items: string[]
      stringSet?: (1 | 2 | 3 | 4 | 5 | 6)[]
      fretRange?: [number, number]
      rootInBass?: boolean
    }
  /** The construction table for a set of qualities, read from the registry. */
  | { kind: 'formula'; caption?: string; qualities: string[] }
  /** The physical moves that produce an interval. */
  | { kind: 'intervalshapes'; caption?: string; interval: string }
  /** A pointer into the tool where this idea becomes usable. */
  | { kind: 'try'; screen: ScreenId; body: string }

export interface Lesson {
  id: string
  title: string
  summary: string
  blocks: Block[]
}

export const LESSONS: Lesson[] = [
  /* ---------------------------------------------------------------- */
  {
    id: 'the-neck',
    title: 'The neck is a ruler',
    summary: 'One fret is the smallest step in music. Everything else is counting.',
    blocks: [
      {
        kind: 'text',
        body:
          'One fret is a **half step** — the smallest distance in Western music. ' +
          'Move up one fret and you have moved up one half step. That is the whole ' +
          'of it, and it is the fact everything else in this app is built on.',
      },
      {
        kind: 'text',
        body:
          'Two frets make a **whole step**. Twelve frets bring you back to the note ' +
          'you started on, an **octave** higher — same letter, same name, higher voice.',
      },
      {
        kind: 'fretboard',
        caption:
          'The low E string. Fret 0 is E, and so is fret 12 — the same note, twelve half steps up.',
        fretRange: [0, 12],
        dots: [
          { string: 6, fret: 0, label: 'E' },
          { string: 6, fret: 12, label: 'E' },
        ],
      },
      {
        kind: 'note',
        body:
          'Notice the frets get closer together as you go up. That is not a drawing ' +
          'quirk — it is how the neck is actually built, and it is why a stretch that ' +
          'is impossible at the first fret can be comfortable at the ninth.',
      },
      {
        kind: 'text',
        body:
          'A piano player has to learn where the half steps are, because on a keyboard ' +
          'they are hiding between the black keys in an uneven pattern. You do not have ' +
          'that problem. **Every fret is a half step, everywhere on the neck.** That is ' +
          'the guitar being easier than the piano, and almost no book says so.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'intervals',
    title: 'Intervals: distance with a name',
    summary: 'The gap between two notes, counted in frets and named by where it lands.',
    blocks: [
      {
        kind: 'text',
        body:
          'An **interval** is the distance between two notes. On a guitar you can ' +
          'measure it by counting frets, and for a long time that is all you need.',
      },
      {
        kind: 'text',
        body:
          'But an interval carries two pieces of information, and the second one is ' +
          'where beginners get stuck. It has a **size in frets**, and it has a ' +
          '**number** saying which step of the scale it lands on. Both matter, and ' +
          'they are not the same thing.',
      },
      {
        kind: 'text',
        body:
          'Here is why. `b3` and `#9` are both **three frets** above the root. ' +
          'Identical distance, identical sound. But one is a flattened *third* and the ' +
          'other is a sharpened *ninth*, and that difference is what separates a minor ' +
          'chord from a Hendrix chord. Same fret, different job.',
      },
      {
        kind: 'intervalshapes',
        caption:
          'A minor 3rd is three frets — but that is only true on one string. Across ' +
          'strings it becomes a shape, and the shape changes depending which pair you are on.',
        interval: 'm3',
      },
      {
        kind: 'note',
        body:
          'Look at the last row. Every adjacent string pair is five frets apart except ' +
          'G to B, which is four. That single irregularity is why so many shapes need ' +
          '"one extra fret" when they cross those two strings, and it is the most ' +
          'useful thing to know about standard tuning.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'major-scale',
    title: 'The major scale is the ruler',
    summary: 'Seven notes that everything else gets measured against and numbered from.',
    blocks: [
      {
        kind: 'text',
        body:
          'Almost every name in music — `maj7`, `m7b5`, `#9`, `b13` — is describing ' +
          'something **relative to the major scale**. Learn the ruler and the names stop ' +
          'being arbitrary.',
      },
      {
        kind: 'text',
        body:
          'The major scale is seven notes, built by this fret pattern from the root: ' +
          '**2, 2, 1, 2, 2, 2, 1**. Whole, whole, half, whole, whole, whole, half. ' +
          'Start anywhere on any string, follow that, and you have a major scale.',
      },
      {
        kind: 'fretboard',
        caption:
          'C major along the A string. The gaps are 2-2-1-2-2-2-1, and the two ' +
          'one-fret gaps are the half steps: 3 to 4 and 7 to 8.',
        fretRange: [2, 16],
        dots: [
          { string: 5, fret: 3, label: '1' },
          { string: 5, fret: 5, label: '2' },
          { string: 5, fret: 7, label: '3' },
          { string: 5, fret: 8, label: '4' },
          { string: 5, fret: 10, label: '5' },
          { string: 5, fret: 12, label: '6' },
          { string: 5, fret: 14, label: '7' },
          { string: 5, fret: 15, label: '1' },
        ],
      },
      {
        kind: 'text',
        body:
          'Those seven notes get numbered **1 through 7**. From now on, when this app ' +
          'says `3` it means the third note of the major scale from the root, and `b3` ' +
          'means that note lowered one fret. That is the entire naming system.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'building-chords',
    title: 'Chords are stacked thirds',
    summary: 'Take the scale, start somewhere, and skip every other note.',
    blocks: [
      {
        kind: 'text',
        body:
          'A chord is built by taking a scale and **skipping every other note**. ' +
          'Start on 1, skip 2, take 3, skip 4, take 5. That is a **triad** — three notes, ' +
          '`1 3 5` — and it is the smallest thing that sounds like a chord.',
      },
      {
        kind: 'text',
        body:
          'Keep going and skip one more: take 7 as well. Now you have a **seventh ' +
          'chord**, `1 3 5 7`, which is where most of the music you play lives.',
      },
      {
        kind: 'fretboard',
        caption:
          'C major along the A string again, with 1, 3, 5 and 7 filled in. The hollow ' +
          'dots are the scale notes you skipped.',
        fretRange: [2, 16],
        dots: [
          { string: 5, fret: 3, label: '1' },
          { string: 5, fret: 5, label: '2', ghost: true },
          { string: 5, fret: 7, label: '3' },
          { string: 5, fret: 8, label: '4', ghost: true },
          { string: 5, fret: 10, label: '5' },
          { string: 5, fret: 12, label: '6', ghost: true },
          { string: 5, fret: 14, label: '7' },
        ],
      },
      {
        kind: 'text',
        body:
          'Keep stacking past the octave and you get the **extensions**: 9, 11 and 13. ' +
          'Those are just 2, 4 and 6 an octave higher, renamed to say "there is a 7th ' +
          'underneath me". That is the only difference between `add9` and `9`.',
      },
      {
        kind: 'formula',
        caption: 'The common chords, read straight out of the app’s own registry.',
        qualities: ['maj', 'min', '7', 'maj7', 'm7', 'm7b5', 'dim7', '9', '13'],
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'chord-quality',
    title: 'The 3rd and the 7th decide everything',
    summary: 'Two notes tell you what a chord is. The rest is furniture.',
    blocks: [
      {
        kind: 'text',
        body:
          'Look at that table again and something jumps out. The root is always there. ' +
          'The 5th is almost always plain. What actually **changes between chords is the ' +
          '3rd and the 7th**.',
      },
      {
        kind: 'text',
        body:
          'The **3rd** decides major or minor. A `3` is four frets above the root and ' +
          'sounds bright; a `b3` is three frets and sounds dark. One fret apart, and it ' +
          'is the single most consequential note in the chord.',
      },
      {
        kind: 'text',
        body:
          'The **7th** decides what flavour of seventh chord you have. A `7` (eleven ' +
          'frets, a half step below the octave) sounds settled and dreamy. A `b7` (ten ' +
          'frets) sounds restless and wants to move somewhere.',
      },
      {
        kind: 'chords',
        caption:
          'Every combination of the two. Left to right: 3 and 7, 3 and b7, b3 and b7, ' +
          'b3 and 7. Same root, same 5th, four completely different chords.',
        items: ['Cmaj7', 'C7', 'Cm7', 'CmMaj7'],
        stringSet: [2, 3, 4, 5],
        fretRange: [1, 6],
        rootInBass: true,
      },
      {
        kind: 'text',
        body:
          'That is the whole grid: two choices of 3rd times two choices of 7th. Those ' +
          'four cover most of what you will ever play, and you can move between them ' +
          'by shifting **one finger by one fret**.',
      },
      {
        kind: 'text',
        body:
          'There is one common chord where this is not the story. In `m7b5` — the ' +
          'half-diminished — the 3rd and 7th are the same as a plain `m7`, and it is ' +
          'the **5th** that drops. It is the exception worth knowing precisely because ' +
          'everything else follows the rule.',
      },
      {
        kind: 'note',
        body:
          'These two notes are called the **guide tones**, and they are why you can play ' +
          'a convincing accompaniment with two fingers. Drop everything else and the ' +
          'harmony is still unmistakable.',
      },
      {
        kind: 'try',
        screen: 'improv',
        body:
          'Set the Improv screen to "Guide tones" and step through a progression. Two ' +
          'notes per chord, and you can still hear exactly what the changes are doing.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'degrees',
    title: 'Why this app shows numbers, not letters',
    summary: 'A shape labelled in degrees is the same shape in all twelve keys.',
    blocks: [
      {
        kind: 'text',
        body:
          'Every dot in this app is labelled with what it **does** in the chord — `R`, ' +
          '`3`, `5`, `b7` — rather than what it is called. That is deliberate, and it is ' +
          'the single biggest reason the app will teach you faster than a chord book.',
      },
      {
        kind: 'text',
        body:
          'A shape labelled `C E G B` is true in exactly one place. The same shape ' +
          'labelled `R 3 5 7` is true **everywhere on the neck, in every key**. Move it ' +
          'up two frets and the letters all change while the numbers stay exactly the same.',
      },
      {
        kind: 'chords',
        caption:
          'The same grip at two positions. The letters would be completely different; ' +
          'the degrees are identical, which is what makes it one shape rather than two.',
        items: ['Cmaj7', 'Dmaj7'],
        stringSet: [2, 3, 4, 5],
        fretRange: [1, 9],
        rootInBass: true,
      },
      {
        kind: 'text',
        body:
          'It also tells you how a note will **behave**. Knowing a note is "F" tells you ' +
          'nothing. Knowing it is the `b7` tells you it wants to fall by a half step — ' +
          'and it will, over and over, for the rest of your playing life.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'voicings',
    title: 'One chord, many shapes',
    summary: 'A chord is a set of notes, not a grip — and you can leave some out.',
    blocks: [
      {
        kind: 'text',
        body:
          'A chord is a **set of notes**. It is not a shape. Any grip that sounds those ' +
          'notes is that chord, and on a guitar there are usually dozens. Each one is ' +
          'called a **voicing**.',
      },
      {
        kind: 'text',
        body:
          'Voicings differ in which note is on the bottom, which is on top, how spread ' +
          'out they are, and which notes are left out entirely.',
      },
      {
        kind: 'chords',
        caption: 'Six voicings of the same chord. All of them are Cmaj7.',
        items: ['Cmaj7', 'Cmaj7', 'Cmaj7', 'Cmaj7', 'Cmaj7', 'Cmaj7'],
      },
      {
        kind: 'text',
        body:
          'You can **leave notes out**, and you should. The 5th goes first — it adds ' +
          'almost nothing and nobody misses it. The **root** can go too, when a bass ' +
          'note or the next chord is covering it. What you cannot drop is the tone the ' +
          'chord is named for: a `maj9` with no 9th in it is just a `maj7`.',
      },
      {
        kind: 'note',
        body:
          'This is the part that matters most for your hands. You do not need six ' +
          'strings or four fingers to play a full-sounding chord. Root, 3rd and 7th is ' +
          'often better than all of it.',
      },
      {
        kind: 'try',
        screen: 'dictionary',
        body:
          'The Dictionary generates every voicing of a chord the neck allows and ranks ' +
          'them by what they cost your hands. Try Cmaj7 and watch what it drops.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'numbers',
    title: 'Keys, and why charts use numbers',
    summary: 'Number the chords instead of naming them and the song fits any key.',
    blocks: [
      {
        kind: 'text',
        body:
          'A **key** is a home base — a major scale that a piece of music is built from. ' +
          'In the key of C, the seven notes of the C major scale each get a chord built ' +
          'on them, and those seven chords are most of what the song will use.',
      },
      {
        kind: 'formula',
        caption:
          'Build a seventh chord on each degree of a major scale and this is what you ' +
          'get, every time, in every key.',
        qualities: ['maj7', 'm7', 'm7', 'maj7', '7', 'm7', 'm7b5'],
      },
      {
        kind: 'text',
        body:
          'Notice the `7` chord only happens on **one** degree — the fifth. That is why ' +
          'a dominant chord sounds like it is pointing somewhere: in any given key there ' +
          'is only one of them, and it points home.',
      },
      {
        kind: 'text',
        body:
          'Because the pattern is identical in every key, you can write a chart in ' +
          '**numbers** instead of letters. `1 6m 2m 5` is a song. `C Am Dm G` is that ' +
          'same song in one key only. Numbers travel; letters do not.',
      },
    ],
  },

  /* ---------------------------------------------------------------- */
  {
    id: 'over-the-chord',
    title: 'Playing over a chord',
    summary: 'Which notes are safe, which are colour, and which lean on something.',
    blocks: [
      {
        kind: 'text',
        body:
          'When you solo, the notes available to you over a chord fall into three ' +
          'groups, and knowing which is which is most of what "playing the changes" means.',
      },
      {
        kind: 'text',
        body:
          '**Chord tones** are the notes of the chord itself. They cannot sound wrong. ' +
          'Land on them, hold them, end phrases on them.',
      },
      {
        kind: 'text',
        body:
          '**Tensions** are the other scale notes that sit clear of the chord tones — ' +
          'the 9ths and 13ths. Colour you can land on.',
      },
      {
        kind: 'text',
        body:
          '**Avoid notes** are scale notes sitting a **half step above a chord tone**. ' +
          'They lean on the note below and want to move. Fine passing through, rough ' +
          'sitting on. The classic one is the 4th over a major chord — it is one fret ' +
          'above the 3rd and it fights it.',
      },
      {
        kind: 'chordmap',
        caption:
          'Cmaj7 across the first five frets. Filled dots are chord tones, outlined are ' +
          'tensions, and the dashed red one is the avoid note.',
        chord: 'Cmaj7',
        fretRange: [0, 5],
      },
      {
        kind: 'note',
        body:
          'Nothing here is a rule about what you are allowed to play. An avoid note ' +
          'played deliberately and resolved is how half of jazz works. The point is to ' +
          'know which notes will fight you, so that when one does it is because you meant it.',
      },
      {
        kind: 'try',
        screen: 'improv',
        body:
          'The Improv screen shows all three groups at once, and recolours them as the ' +
          'chords change under your hand. Lock a position and watch what happens.',
      },
    ],
  },
]

export const lessonById = (id: string): Lesson | undefined =>
  LESSONS.find((lesson) => lesson.id === id)
